version: '3.9'
services:
  db:
    container_name: 'mysql8.0'
    image: 'mysql:8.0'
    volumes:
      - ./data/mysql:/var/lib/mysql
    command: mysqld --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: always
    tty: true
    ports:
      - 30066:3306
    expose:
      - '30066'
    environment:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_PASSWORD
    networks:
      - wp-network
  wordpress:
    container_name: 'wordpress-app'
    depends_on:
      - db
    image: 'wordpress:5.9'
    ports:
      - 6700:80
      - 443:443
    environment:
      - WORDPRESS_DB_HOST
      - WORDPRESS_DB_USER
      - WORDPRESS_DB_PASSWORD
      - WORDPRESS_DB_NAME
      - WORDPRESS_CONFIG_EXTRA
    volumes:
      - "./wordpress:/var/www/html"
      - "./wp-content:/var/www/html/wp-content"
    networks:
      - wp-network
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin:5
    restart: always
    ports:
      - 7070:80
    environment:
      - PMA_HOST
      - MYSQL_ROOT_PASSWORD
    networks:
      - wp-network
networks:
  wp-network:
    driver: bridge